// <auto-generated />
using System;
using Entertainment_travel_booking_website.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entertainment_travel_booking_website.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260129151613_InitialTable")]
    partial class InitialTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdditianActivitiesTrip", b =>
                {
                    b.Property<int>("AdditianActivitiesId")
                        .HasColumnType("int");

                    b.Property<int>("TripsId")
                        .HasColumnType("int");

                    b.HasKey("AdditianActivitiesId", "TripsId");

                    b.HasIndex("TripsId");

                    b.ToTable("AdditianActivitiesTrip");
                });

            modelBuilder.Entity("Entertainment_travel_booking_website.Models.ActivitiesSupImg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdditianActivitiesId")
                        .HasColumnType("int");

                    b.Property<string>("SupImg")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdditianActivitiesId");

                    b.ToTable("activitiesSupImgs");
                });

            modelBuilder.Entity("Entertainment_travel_booking_website.Models.AdditianActivities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("additianActivites");
                });

            modelBuilder.Entity("Entertainment_travel_booking_website.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PricePerNight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("hotels");
                });

            modelBuilder.Entity("Entertainment_travel_booking_website.Models.HotelSupImg", b =>
                {
                    b.Property<string>("SupImg")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("SupImg", "HotelId");

                    b.HasIndex("HotelId");

                    b.ToTable("hotelSupImgs");
                });

            modelBuilder.Entity("Entertainment_travel_booking_website.Models.Room", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HotelId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("locationInHotel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("HotelId");

                    b.ToTable("rooms");
                });

            modelBuilder.Entity("Entertainment_travel_booking_website.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DiscountedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxPeople")
                        .HasColumnType("int");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("trips");
                });

            modelBuilder.Entity("Entertainment_travel_booking_website.Models.TripAdditianActivities", b =>
                {
                    b.Property<int>("tripId")
                        .HasColumnType("int");

                    b.Property<int>("additianActivitiesId")
                        .HasColumnType("int");

                    b.Property<string>("NotesOBT")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("tripId", "additianActivitiesId");

                    b.HasIndex("additianActivitiesId");

                    b.ToTable("tripAdditianActivities");
                });

            modelBuilder.Entity("Entertainment_travel_booking_website.Models.TripSupimage", b =>
                {
                    b.Property<string>("SupImg")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("SupImg", "TripId");

                    b.HasIndex("TripId");

                    b.ToTable("TripSupimage");
                });

            modelBuilder.Entity("AdditianActivitiesTrip", b =>
                {
                    b.HasOne("Entertainment_travel_booking_website.Models.AdditianActivities", null)
                        .WithMany()
                        .HasForeignKey("AdditianActivitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entertainment_travel_booking_website.Models.Trip", null)
                        .WithMany()
                        .HasForeignKey("TripsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entertainment_travel_booking_website.Models.ActivitiesSupImg", b =>
                {
                    b.HasOne("Entertainment_travel_booking_website.Models.AdditianActivities", "AdditianActivities")
                        .WithMany()
                        .HasForeignKey("AdditianActivitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdditianActivities");
                });

            modelBuilder.Entity("Entertainment_travel_booking_website.Models.HotelSupImg", b =>
                {
                    b.HasOne("Entertainment_travel_booking_website.Models.Hotel", "Hotel")
                        .WithMany("HotelSupImgs")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Entertainment_travel_booking_website.Models.Room", b =>
                {
                    b.HasOne("Entertainment_travel_booking_website.Models.Hotel", null)
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId");
                });

            modelBuilder.Entity("Entertainment_travel_booking_website.Models.TripAdditianActivities", b =>
                {
                    b.HasOne("Entertainment_travel_booking_website.Models.AdditianActivities", "additianActivities")
                        .WithMany()
                        .HasForeignKey("additianActivitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entertainment_travel_booking_website.Models.Trip", "trip")
                        .WithMany()
                        .HasForeignKey("tripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("additianActivities");

                    b.Navigation("trip");
                });

            modelBuilder.Entity("Entertainment_travel_booking_website.Models.TripSupimage", b =>
                {
                    b.HasOne("Entertainment_travel_booking_website.Models.Trip", "Trip")
                        .WithMany("TripSupimages")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Entertainment_travel_booking_website.Models.Hotel", b =>
                {
                    b.Navigation("HotelSupImgs");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Entertainment_travel_booking_website.Models.Trip", b =>
                {
                    b.Navigation("TripSupimages");
                });
#pragma warning restore 612, 618
        }
    }
}
